sdmg15/Best-websites-a-programmer-should-visit

README.md

Multireddit links should contain full username to be accessible by everyone. The change also features automatic whitespace formatting.

Update multireddit links

---

README.md

wiki.c2.com is a goldmine of information on design patterns and object oriented programming.

Adds wiki.c2.com to general coding advice section

---

README.md

As mentioned in  #11.  There are probably others but these are the two I've used...

Proposed fix to #11

---

README.md

Collection of style guide fixes for ( Link : Description ) where needed. Fixed a few links that were improperly formatted and added a nested list.

Consistent styling of link : description

---

README.md

I think it is incredibly useful for new programmers or anyone as it allows to quickly see what the best way for learning a topic is and how it relates to other topics.

Adds Learn Anything website

---

README.md

Added godbolt.org Compiler Explorer to the Online Compiler and Sharing Code snippets section.  The Compiler Explorer is a great tool for exploring how different compilers optimize code.

Added godbolt.org Compiler Explorer

---

README.md

Kadenze has a variety of creative programming courses covering topics from Machine Learning (and Tensorflow), Processing, Arduino, audio programming, etc.

Adding Kadenze link to the MOOC section of the readme

---

README.md

Added AlternativeTo: Crowdsourced software recommendations

Added AlternativeTo

---

README.md

this is a fantastic beginner resource.

adding exercism resource

---

README.md

Add Cloud 9 and GitHub gist to the online compilers and code sharing section

Add Cloud 9 and Github Gist

---

README.md

Unsuful text on line 339 and 343.

Revert "Add Cloud 9 and Github Gist"

---

README.md

+Added description to ACM TechNews
+Added Library Genesis to "Free Books" sections
+Added descriptions to "Bored of CS" section
-Changed broken URL of Barcroft TV to the correct URL
-Moved nayuki.io to "Blogs" section, as it doesn't really give practice problems, it just walks through the author's solutions

Added descriptions, slight cleanup, one new link

---

README.md

I think these two belong here.

added CodePad and JSFiddle

---

README.md

Added index entry and category heading

Added general tools section

---

README.md

Few links fixed and changes all "-" to ":";

---

README.md

Added in another YouTube channel as well as a list of podcasts.

Added in a podcasts section

---

README.md

[Airbnb JS Style Guide](https://github.com/airbnb/javascript) : A mostly reasonable approach to JavaScript

Added Airbnb's JS style guide

---

README.md

Hi,
I have added a 1000 Mega Projects repo link also added a Internship guide which is very helpful.

added 1000 Projects link and internship guide link

---

README.md

* Updated/Added Design Patterns Websites under General Coding advice.
* Updated C++ FAQ Websites under 'Sites related to your preferred programming language'.
Signed-off-by: Jos Collin <jcollin@redhat.com>

README.md: General Coding advice and Preferred Programming Language

---

README.md

Livecoding.tv -> Liveedu.tv

---

README.md

Adding "codingame.com" = another competitive programming website

Add_website_to_see

---

README.md

This is a very good website with hundreds of problems supporting multiple languages. Problems are well presented and range in difficulty. Some are VERY hard. Its quite an underdog site it seems since most don't know of it.
Enjoy!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sdmg15/best-websites-a-programmer-should-visit/64)

UVA online added to competitive websites section.

---

README.md

Added "Developer Tea" link to list of podcasts.

Added podcast

---

README.md

Codewars has a diverse set of kata, and it can get pretty competitive in terms of rank/cleverness. Seemed like it may be a good fit for this list.

Adding codewars.com to the competitive programming section.

---

README.md

A few great videos to watch for web developers.

added Netflix UI Engineering YouTube channel

---

README.md

The youtube links for the documentary, Machine that Changed the World, are not working. So I have added new links for them which I think are correct. Please verify them and approve the changes.

Update documentary links

---

README.md

blog.might.net added twice in Blogs of Developers

blog.might.net added twice in Blogs of Developers

---

README.md

Added missing `1` in "What every programmer should know about memory, Part **1**"
Thank you for this awesome list BTW  😃

Add missing number in "Part 1"

---

README.md

Adds Angular 1 style guide by John Papa (This is the officially endorsed style guide by the Angular team).
Thought this should be added considering how many developers use Angular, and more importantly how many tend to use it in a non-angular way.

Adds Angular 1 Style Guide

---

README.md

Add the great Software Engineering Daily podcast (https://softwareengineeringdaily.com)

Add Software Engineering Daily podcast

---

README.md

Updated index to include Podcasts

---

README.md

Sorry about the whitespace changes, my editor removes whitespace from end of lines.

Add WakaTime

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

**Disclaimer: The following is a personal contribution, and does not necessarily reflect the views of GitHub, my employer.**
A code of conduct is important because it promotes moral behavior, acts as a guideline for ethical decision making, enhances the reputation of an organization, prevents negative legal effects, encourages positive relationships, acts as a reference for solving ethical dilemmas and prevents discrimination or harassment.
Harassment and abuse are significant factors in preventing the entire community of tech companies, user groups, open source projects, and other organizations and events from being truly diverse and welcoming to participation.
Also, a well-written code of conduct clarifies an organization's mission, values and principles, linking them with standards of …

Adhering to the Contributor Covenant Code of Conduct

---

README.md

Added Tutorials Section into Index

---

README.md

The addition of 'devRant.io' to the 'When you get bored from CS related stuff' section.

Added devRant

---

README.md

Right now you get the Github 404 page

missing http:// for "Summer Internship: The Ultimate Guide" link

---

README.md

List of books on Zed Shaw's website.

Added 'Become a Programmer, Motherfucker'

---

README.md

Added description for JavaScript Jabber

Added podcast description

---

README.md

Awesome Compilers is a vertical that I created a couple of weeks ago. It is basically a curated list of awesome resources, learning materials, tools, frameworks, platforms, technologies and source code projects in the field of Compilers, Interpreters and Runtimes.

Added the Awesome Compilers vertical.

---

README.md

Added the twitch programming community to `Watch others code`

added twitch.tv

---

README.md

Missed error in format in link : description

Fixed invalid formatting on description

---

README.md

DevOpsLinks is an online community for people interested in DevOps, cloud computing, Docker, microservices development and many other interesting subjects.

add devopslinks

---

README.md

I fixed the error on the links :)

adding devopslinks community website

---

README.md

Added Ridddle, a youtube channel about science, mainly the universe and space, but also other science-related stuff.

Add Ridddle to the "When you get bored of CS related stuff" section

---

README.md

Streams from people who is reverse engineer in google

Gynvael EN YT streams

---

README.md

Extra spaces, incorrect formatting, extra characters all removed

Collection of formatting fixes

---

.travis.yml

Added URL again, seems like quora is more of a problem than I thought

Update white list with CI

---

README.md

The first part is unavailable due to copyright claims.

remove part 1 of The Machine that Changed the World

---

README.md

Replace "programming principles" (closes #174)

---

README.md

Fixed link format that is not allowing markdown to render properly

Invalid markdown format

---

README.md

New Wes Bos and Scott Tolinkski podcast

Added newly released podcast to list

---

README.md

Removed copy/pasted bullet character from description.

Remove character from description

---

README.md

Add podcast and blog

---

README.md

Pluralsight has a lot of great courses that prepare would-be engineers for their work like the AWS Certified DevOps Engineer course.

Added Pluralsight

---

README.md

Added CodeSchool to the list. 
By the way, nice work! :+1:  :smile:

Added CodeSchool

---

README.md

Changes:
- alphabetical order
- uppercased Topcoder
- added codility.com

Competitive programming update

---

README.md

xda android developer forum added

Added XDA in blogs section.

---

README.md

Added sites

---

README.md

@sdmg15 I think you should update the CONTRIBUTING.md to ask contributors to list their contributions alphabetically.

Listed everything alphabetically

---

README.md

Added descriptions and fixed 1 formatting error.

Added descriptions to all podcasts

---

README.md

Add news section -> Hacker Noon

---

README.md

Link copied into page from earlier bad commit

Remove errant link

---

README.md

One of the best blog writers  i have seen

Add Daniel Lemire's blog

---

README.md

added khan academy

---

README.md

- Add Python code style links
- Add Hackerrank
- Add Scikit-learn to Learn AI

Add Python code style links

---

CONTRIBUTING.md
README.md

Add Reddit/r/programming subreddit to News section
Fix typo to change 'considere' to 'consider' in CONTRIBUTING.md file

Add Reddit/r/programming to News section

---

README.md

Another online regex tester, user friendly and contains lots of examples

Added link to regexr.com

---

README.md

gist.github allows to share code both privately and publicly.

Added github gist

---

README.md

change https to http

---

README.md

added more websites in open source section

added some more websites

---

README.md

Added entry in the Podcasts section

Podcast addition

---

README.md

add devdocs.io into Everything in one place section

Add devdocs.io

---

README.md

Removed duplicate reddit link fixes #260

---

README.md

Added a link to a normalization article.

Added normalization link

---

README.md

https://freecourses.github.io/#/

Adding FreeCourses

---

README.md

Awesome channel for web development.

Added traversymedia in youtube  section.

---

README.md

I have added an awesome source of Competitive programming where you can learn coding by doing practice in languages like C, C++, Java, and Python.

Adding URI Online Judge to Competitive programming section

---

README.md

I have given space for writing down the links in the categories.

Added Categories Internships and Jobs

---

README.md

For Internships: [Internshala](https://internshala.com/)
For Jobs: [Paysa](https://www.paysa.com/jobs)

Added Internshala in Internships category and Paysa in Jobs category.

---

README.md

[Chegg](http://www.chegg.com/)
[LetsIntern](https://www.letsintern.com/)

Added Chegg and Letsintern in Internship Section

---

README.md

[Glassdoor](https://www.glassdoor.co.in)

Added Glassdoor, Indeed, Dice etc.

---

README.md

I have added a new resource in the Jobs Section. Please have a look and try it.
[The Muse](https://www.themuse.com) : Find everything you need to succeed from dream jobs to career advice. You can do a lot here on The Muse like exploring companies, browsing jobs, career advice,  discover careers,  career coaching. Try it.

Added The Muse in Jobs Section

---

README.md

Added [Instahyre](https://www.instahyre.com) in the jobs section. This is an awesome platform for jobs searching and it also recommends you by email.

Added Instahyre in the jobs section

---

README.md

[ZipRecruiter](https://www.ziprecruiter.com) : The smartest way to get hired.

Added ZipRecruiter in the jobs section

---

README.md

https://hackr.io/tutorials/learn-c-plus-plus

Added "Recommended C++ Resources"

---

README.md

Adding to 'When you get bored from CS related stuff' a fun little game that is made for cs people.

Adding Regex Crossword

---

README.md

Added a link to this monumental and widely adopted AI textbook! 
http://aima.cs.berkeley.edu/

Added Artificial Intelligence: A Modern Approach

---

README.md

ref: https://github.com/sdmg15/Best-websites-a-programmer-should-visit/pull/120

Recover Revolution OS Linux Documentary

---

README.md

I added Perfect Intern to the internship section. It is an internship website for programmers that will help match them with paying internships. Some companies will pay students and provide room and board. I also sorted the internship list and the job site list while I was there.

Added Perfect Intern to the intern list and cleaned up job section

---

README.md

Online version of the Learning JavaScript Design Patterns published by O'Reilly, released by the author Addy Osmani under CC BY-NC-ND 3.0

Add Javascript Design Pattern

---

README.md

ExtendsClass provides several online tools (API clients, Regex/XPath testers, SQLite browser...)

add a link to extendsclass (general tool)

---

README.md

Also, add some detail to the description

Remove space in StackShare

---

README.md

Hello,
I'm actively creating this job board to help developers find jobs more easily and hope we could include it into this list. 
thanks a lot,
David

Add developer job board Devsnap

---

README.md

Add a new documentary: The Internet's Own Boy: The Story of Aaron Swartz.

Add new documentary about Aaron Swartz

---

README.md

Added coder.com, a web based Development Environment thats using Visual Studio Code

Added coder.com

---

README.md

Adding Kudvenkat link to youtube channels list. Here is the links of the channel https://www.youtube.com/user/kudvenkat/. This is a useful resource for Microsoft .NET technologies and SQL Server tutorials.

adding KudVenkat to youtube channels list

---

README.md

Hey there,
This is my personal blog where I write about programming and design in general.
Regards!

Add amitmerchant.com

---

README.md

I thought this might be a helpful resource for your list. Let me know if this belongs in a different section. Thanks!

Adding a webhooks guide

---

README.md

Added this site link, since I found it to be a very curated, and well updated site on tech news.

Add WCCF Tech site link

---

README.md

Analyzing the links, I found a ")" randomly in line 203. Removed for a better appearance and standardization.

[LITTLE PROBLEM] In line 203 of README.md

---

README.md

For better understanding Algorithms, Data Structures and Computer Engineering from one of the best professors in the world, MIT OCW is the perfect place to gain all these.
Youtube Link to [MIT OCW](https://www.youtube.com/user/MIT/)

Added MIT OpenCourseWare

---

README.md

SwissDev Jobs is a dev dedicated job board from Switzerland

Add SwissDev Jobs - job board

---

README.md

This Pull request is regarding the addition of MLCOURSE.ai to the AI section

Added mlcourse.ai

---

README.md

Created a link to the top at the end of the topic
Issue: https://github.com/sdmg15/Best-websites-a-programmer-should-visit/issues/407

add link at the end of the top

---

README.md

@sdmg15 
Could you please review my P.R ?

added new Youtube channel for reference

---

README.md

Index says: Sites related to your preferred programming language (For me Java)
Actual Content says: Sites related to your preferred programming language (For me C++)

Section mismatch between Index and Actual Content

---

README.md

Update readme.md in General Tools and Coding Style section

Add Crontab Guru in README.md

---

README.md

We Work Remotely is the largest remote work community in the world. With over 2.5M monthly visitors, WWR is the #1 destination to find and list incredible remote jobs.

Added weworkremotely for Jobs

---

README.md

A free course provided by Reaktor and University of Helsinki.

Added item in 'Learn AI'

---

README.md

Add new link in Competitive programming session

add Developer Roadmaps

---

README.md

In Competitive programming list,the name Code Fights is was changed to Code Signal in 2018.So I changed the website and name of CodeFights to CodeSignal.

Changing name and website

---

README.md

Added carbon.now.sh, a tool to generate sourcecode images of your codesnippets.

Add carbon.now.sh

---

README.md

First of all, I arranged the contents of the 'Everything in one place' category in letter order. I then added a site that would fit the category.

'Everything in one place' category editing

---

README.md

Eric Normand is a functional programming expert and in his podcast LispCast, he talks about functional programming concepts. He also publishes the podcasts in video format on his youtube channel. All podcasts have written transcripts.

Added LispCast and Eric Normand to podcasts/youtube channels

---

README.md

Added edabit as another resource for javascript coding challenges

Added edabit challenges link

---

README.md

Included a new resource to the "News" Section.

Better Programming News Resource

---

README.md

This PR includes a good resource about software architecture maintained by Martin Fowler.

Add Martin Fowler's Software Architecture Guide

---

README.md

Article on Tensorflow certification is added

Article on Tensorflow Certification 

---

README.md

added commandlinefu

---

README.md

Added the website Interview Cake to the interview prep section.

add interview cake to interview prep section

---

README.md

Add CSS Tricks

---

README.md

Added : https://www.youtube.com/c/MurtazasWorkshopRoboticsandAI in Youtube channels section with alphabetical order.

Added Murtaza's OpenCV Robotics and AI Youtube channel

---

README.md

I have checked the links once again and removed them which are not working. It is good to contribute to your Repo. Thank you

 Deleted all the dead links

---

README.md

This is probably the most popular site to find relevant answers to your programming questions fast. "GIYF" (Google Is Your Friend) is a mantra among developers, and should probably be the best first place to start looking if you get stuck (besides the docs for language/library/frameworks/etc....but you can also just Google those 😉 ).

Add Google Search

---

README.md

I couldn't decide whether it would be better in "General Tools" or "Everything in one place" but I picked the latter.

Moved gitignore into better category

---

README.md

I thought this might be a useful resource for devs looking for help with design (and they're free). Full disclosure: I created them, and  some developers have used them to help launch their projects.

Add SaaS Design - free UI templates for developers

---

README.md

Hi 👋🏻 just replacing this line with gender-neutral language. Hope that's all right 👍🏻

Replace 'you guys' with 'you all'

---

README.md

[Json API App](https://www.jsonapi.co/) : Single repository for everything you need to build better products as a developer. API, DB, Queue, Server, Webhooks, Bin, Tools, Podcasts etc. Everything you need to build super apps that our world needs.

Add Json API App

---

README.md

0-Download: The True Story of the Internet (https://www.youtube.com/playlist?list=PL_IlIlrxhtPMqW4b0-v8OgLvFZQes6SoZ) : unavailable
1-How does CPU execute a program (https://www.youtube.com/watch?v=42KTvGYQYnA): removed
2-Project Code Rush (https://www.youtube.com/watch?v=a-49a_CjH0M): private 
3-Revolution OS Linux Documentary (https://www.youtube.com/watch?v=4vW62KqKJ5A): unavailable
4-Triumph of the Nerds (https://www.youtube.com/playlist?list=PLn-Y3vvQbmHO5WUcBdIWqiUfNawhC1cn3): Does not exist

Removed unavailable links

---

README.md

Added a new youtube channel for data structures and algorithms in java and c++

Added a new youtube channel for Data Structures and Algorithms in C++ & Java

---

README.md

- [dylanaraps](https://github.com/dylanaraps)' [pure-bash-bible](https://github.com/dylanaraps/pure-bash-bible)
- ~~[dylanaraps](https://github.com/dylanaraps)' [pure-sh-bible](https://github.com/dylanaraps/pure-sh-bible)~~
Both guides are quite popular and, more importantly, really useful.
[dylanaraps](https://github.com/dylanaraps) deserves a big thank you.
Signed-off-by: molese <molese@protonmail.com>

Add dylanaraps' pure-bash-bible

---

README.md

Added Kaggle, a must-visit site for all data enthusiasts 👍🏻

Added Kaggle

---

README.md

Link description taken from official website

Add Rust by Example

---

README.md

If you’re a self-taught engineer or bootcamp grad, you owe it to yourself to learn computer science. Thankfully, you can give yourself a world-class CS education without investing years and a small fortune in a degree program 💸.
There are plenty of resources out there, but some are better than others. You don’t need yet another “200+ Free Online Courses” listicle. You need answers to these questions:
Which subjects should you learn, and why?
What is the best book or video lecture series for each subject?
This guide is our attempt to definitively answer these questions.

Add TeachYourselfCS to General Coding advice

---

README.md

Add: The Real Python Podcast

---

README.md

This article describes how to create a blockchain with all the necessary operation from scratch using Python and Flask.

Add Hackernoon article about blockchain in Python

---

README.md

[Library or micro code solutions](https://onelinerhub.com/) : Community library of micro code pieces for popular issues.

Added community code pieces website

---

README.md

It's dying https://meta.stackoverflow.com/questions/415293/sunsetting-jobs-developer-story
merge on april 1st or after

Remove SO jobs

---

README.md

Have Added Scaler Topics links under Coding practice for beginners. Please check the suggested changes

Added One Useful Link

---

README.md

A supportive community for people who are interested or already contributing in open source.

Added link to Eddiehub community for open source contributors

---

README.md

Coderanch is a very friendly place to search for all kinds of programming questions, tutorials as well as jobs. A must for all developers and programmers.

Adding Coderanch to list of websites when stuck

---

CONTRIBUTING.md
pull_request_template.md

Update the Contributing Guidelines to try to provide more clarity on how Pull Requests should be done. Also added this type of PR template to try to ease the review process by enforcing the guidelines on it.
Fixes #1368 
[x] My change follows the [Contributing Guidelines](./CONTRIBUTING.md)
[ ] I have added only one new link to the list.
[ ] I have sorted the link alphabetically under the related section.

Refresh PR policies for the project

---

pull_request_template.md

Updated pull request template

---

README.md

added new site for interview prep - hacktoberfest

---

README.md

Thank You for reading my Pull Request

Ramashankar contribution

---

README.md

Open Source Websites
[+] N-O-D-E

Added open source Website

---

README.md

Added Simplilearn's simplified Machine Learning playlist and corrected some grammatical errors.

---

README.md

#hacktoberfest
Added Sourcegraph to the tools section
Sourcegraph is a tool where you can perform queries for searching repositories

Added Sourcegraph to the Tools section

---

README.md

The site is a great way for beginners to learn interactively

Added url for SQL Zoo for beginners to interactively learn SQL Queries

---

README.md

I added [A Byte of Python](https://python.swaroopch.com), a great introduction to programming concepts in python.
[x] My change follows the [Contributing Guidelines](./CONTRIBUTING.md)
[x] I have added only one new link to the list.
[x] I have sorted the link alphabetically under the related section.

add a byte of python

---

README.md

This link has a collection of Learning guides that helped me learn about Bitcoin and Lightning and is by far the most awesome link that helped me learn about the technology of Bitcoin.

added Bitcoin and Lightning protocol seminar links

---

README.md

Adds article link for "A Developer's Guide to Working with Recruiters"
[x] My change follows the [Contributing Guidelines](./CONTRIBUTING.md)
[x] I have added only one new link to the list.
[x] I have sorted the link alphabetically under the related section.

Add interview article link

---

README.md

* added Rekt - A journalism related to Defi, Web3, Blockchain and security on them.
[ ] My change follows the [Contributing Guidelines](./CONTRIBUTING.md)
[ ] I have added only one new link to the list.
[ ] I have sorted the link alphabetically under the related section.

feat: added Rekt

---

README.md

#HSFDPMUW just helps me finding my pull-requests better. :)
I just sorted the section "CryptoCurrency" in alphabetical order.

Sorted "CryptoCurrency" in alphabetical order (#HSFDPMUW)

---

README.md

#HSFDPMUW just helps me finding my pull-requests better. :)
I just sorted the section "Online Compiler and Sharing Code snippets" in alphabetical order.

Sorted "Online Compiler and Sharing Code snippets" in alphabetical order (#HSFDPMUW)

---

README.md

Added Kody tools to general tools section
Kody Tools has 100+ dev tools including code formatters, converters, and minifiers

Added Kody Tools to General Tools

---

README.md

Added kandi site under General Tools
- [Yes ] My change follows the [Contributing Guidelines](./CONTRIBUTING.md)
- [Yes ] I have added only one new link to the list.
- [Yes ] I have checked that the link that I added does NOT exist in the project already.
- [No ] I have sorted the link alphabetically under the related section. - most of the listings are not alphabetical

Added kandi under General Tools

---

README.md

Added CWE Top 25 to README.md
MITRE - 2022 CWE Top 25 Most Dangerous Software Weaknesses. Helping developers secure their code.

Added CWE Top 25 to README.md

---

README.md

Change Name of Learn AI to artificial intelligence and machine Learning
fix Issuse #1782

Change Name of Learn AI to artificial intelligence and machine learning

---

README.md

Added AtCoder as a prestigious Competitive Programming platform to README.md
Added AtCoder as a widely acclaimed competitive programming platform

Added Competitive Programming platform to README.md

---

README.md

I have added a tool to the everythin at one place section. btechbasics teach the Fundamental concepts of Computer Science Engineering using hands-on exercises, hence it could be an asset for btech students.
- [YES] My change follows the [Contributing Guidelines](./CONTRIBUTING.md)
- [YES] I have added only one new link to the list.
- [ YES] I have checked that the link that I added does NOT exist in the project already.
- [ YES] I have sorted the link alphabetically under the related section.

added btechbasics.in to the everything in one place category

---

README.md

An interesting blog with a very interesting article on our world

Add The Pragmatic Engineer blog

---

README.md

A fully remote, 12-week internship alternative where participants earn a stipend and learn to collaborate on real open-source projects with peers and engineers from top companies.

added open source programme

---

README.md

Added aicollective.tools under Everything in one place section
Explore a curated selection of AI tools and resources at aicollective.tools.

docs: 📝 Added aicollective.tools under Everything in one place section

---

README.md

This web app is the simplest web app with all the stats needed for quick sessions of practice per day or as comfortable.

Add Keybr.com for typing practice

---

README.md

add uber go style guide

---

README.md

change
https://openai.com/robots-that-learn
to
https://openai.com/research/robots-that-learn

Update dead link (robots that learn)

---

README.md

Removed a dead link in the README.md file.
Fixes: #1863 
- Section: [Interview Preparation section,](https://github.com/sdmg15/Best-websites-a-programmer-should-visit/blob/master/README.md#interview-preparation) link: [Core Java Interview questions - Interview question on each topic](http://javahonk.com/core-java-interview-questions/) 
- The link is dead and the site is up for sale, so I've removed the link.

Updated REAMDE.md by removing a dead link.

---

README.md

Fixes: #1866
Removed a dead link in "Interview Section" by the name of:
"How to Answer the Toughest 40 Job Interview Questions/ICS Job Portal]

Update README.md by removing dead link.

---

README.md

Add Pyrexp to General Tools
Add Pyrexp, a regex tester and visualizer for Python, to General Tools

Add Pyrexp to General Tools

---

README.md

Removed [broken link](http://www.dreamincode.net/forums/topic/78802-martyr2s-mega-project-ideas-list/) 
fixes #1893

removed broken link

---

README.md

Added GitHub Codespaces to Online Compiler section
Fixes https://github.com/sdmg15/Best-websites-a-programmer-should-visit/issues/1815

GitHub Codespaces

---

README.md

#1682 issue solved.
Added Imgur Link under General tools.

Update README.md with Imgur link #1682

---

README.md

Add boot.dev to the MOOC section because it is great interactive course.

Add mooc bootdev

---

README.md

I would like to add my remote jobs board: https://jobscollider.com/remote-jobs
I scan 10,000+ companies every day to gather all open jobs, classify each job, filter for remote positions, and post them on my site: https://x.com/oterpr/status/1814711719392076223

Add JobsCollider to README.md

---

README.md

Added a new ML resource that has visual explanations of core ML concepts.
MLU-EXPLAIN - https://mlu-explain.github.io/
Visual explanations of core machine learning concepts Machine Learning University (MLU) is an education initiative from Amazon designed to teach machine learning theory and practical application.

Added a new ML resource that has visual explanations of core ML concepts.

---

README.md

update the website name and link of AngelList to Wellfound

---

README.md

Added prompt engineering tutorial.
I am a beginner in Hacktober fest 2024 and have made my contribution by adding a link for Prompting Guide AI which is an online platform designed to help users create effective prompts for AI models, enhancing the quality and relevance of generated outputs. It offers tips, examples, and best practices to improve user interactions with AI, making it easier to achieve desired results. Please do consider my merging of request as soon as possible.

Added Prompt engineering tutorial 

---

README.md

This commit enhances the README by adding emojis to section headings, improving navigation and visual appeal for users. Key sections like Internships, Jobs, Special Thanks, and Best Websites a Programmer Should Visit are now more engaging and easier to read.

update README with Section Headings and Visuals

---

README.md

Added website to Increase your typing speed while racing

Website to increase typing speed

---

README.md

Add IT-Tools in general tools

---

README.md

I navigated here and it's now just serving ads, nothing useful anymore
Removing a website that no longer is useful

Remove dead website

---

README.md

Add JSONing to General Tools
Add JSONing (my website), a suite of online JSON tools, including a Formatter, Validator, Comparator, JSON Generator, JSONPath Tester, JSON Schema Generator, and Mock API for testing and prototyping.

Add JSONing to General Tools

---

README.md

i added some channels and reordered the Video Tutorial section and News section for better organization and readability.

reordered new section

---

README.md

Ray.so is a powerful tool that helps programmers instantly convert their source code into aesthetic, shareable images. Whether you're sharing a snippet on Twitter, LinkedIn, blog posts, or technical documentation, Ray.so makes your code look clean, readable, and professional.
- [Ray.so](https://www.ray.so/): Beautiful code snippet screenshots.

Added Ray.so(Beautiful code snippet screenshots.) in  General tools section
