sdmg15/Best-websites-a-programmer-should-visit

- README.md
The competition was formerly hosted at http://theaigames.com/ but has since migrated over to riddles.io.
> Add riddles.io to competitive programming

- README.md
Seems that [JavaScript Planet](https://www.youtube.com/channel/UCzVnCG4ItKitN1SCBM7-AbA/videos) had some content violation against YouTube policy.
Removing it then.
> Remove invalid resource - JavaScript Planet

- README.md
code::dive conference (organized by NOKIA Wrocław Technology Center) has its own YouTube channel. Old lectures (2014 and 2015) are on both channels (code::dive's one has them by playlists) while new ones (2016) are only on code::dive's channel and so will it be with upcoming 2017 edition.
Furthermore code::dive conference has its own [web page](http://codedive.pl/), [Facebook profile](https://www.facebook.com/CodeDiveWroclaw/) and [Twitter profile](https://twitter.com/code_dive_pl). However, for the purpose of this list they don't seem as useful as the [YouTube channel](https://www.youtube.com/channel/UCU0Rt8VHO5-YNQXwIjkf-1g) added here.
I am NOKIA Wrocław Technology Center's employee, co-organizer code::dive conference and a speaker there.
> NOKIA Wroclaw Technology Center -> code::dive conference

- README.md
Adding C++Now conference (that seems to be previously named BoostCon). There are lots of lectures there, including ones uploaded just days ago.
> C++Now (BoostCon) conference added.

- README.md
In line 89 " Design Patterns explained in detail with examples. " the word detail is misspelled as detial. Edited and corrected it.
> edited and corrected detial to detail

- README.md
This video is no longer on YouTube. So I think the link is no longer relevant.
> Removes the Revolution OS Linux Documentary link

- README.md
Add link for peoplecanprogram.com, a site that teaches programming
online with an interactive interface and beginner-friendly error messages.
> Add People Can Program link

- README.md
Fixed dev ops link with bad format from latest commit #169. Adjusted spacing
> Fixed devops link formatting error

- README.md
I'd like to include [Solid Tools for Developers](https://soliddevtools.com) (full disclosure: this is a free-to-use web-app I've developed) and [my own personal blog](https://www.andyheathershaw.uk) (I occasionally write about .NET, PHP and databases!)
Thanks.
> Added Solid Tools for Developers and my own blog

- README.md
This change seeks to add Develop for Performance, a website dedicated to high-performance computing, for software architects and developers.  While there are many online resources focused on the academic / theoretical aspects of high-performance computing, there are relatively few oriented toward practical software development.
Currently this website features just content that I've authored.  Anyone wishing to write for Develop for Performance is free to contact me, though I'd like to ensure that new content is of a quality, style. and depth fairly similar to that of the existing content.  There's example code, sometimes specific to C++ and Windows, though the concepts are covered with a range of environments and platforms in mind.
Some info about my background is available here: …
> Add new software development website.

- README.md
Consider adding OWASP. OWASP is an international organization and the OWASP Foundation supports OWASP efforts around the world. OWASP is an open community dedicated to enabling organizations to conceive, develop, acquire, operate, and maintain applications that can be trusted. All of the OWASP tools, documents, forums, and chapters are free and open to anyone interested in improving application security.
> Adding OWASP reference

- README.md
Added Soft Skills Engineering, a weekly advice podcast for software developers. They answer questions about all the stuff you didn't realize you needed to know about being an engineer.
> Added Soft Skills Engineering Podcast

- README.md
LiveEdu.tv is now Education Ecosystem. The currently listed url redirects. I'm not familiar with the old or new website, hopefully it's still a good resource.
Twitch.tv has removed its "communities" feature that the current url links to. I've replaced it with a url to the Science & Technology category. This is often used by streamers who are programming.
Thanks!
> Fix Watch Others Code urls

- README.md
Recently, we launched https://classpert.com - a free search engine for online courses. Our main focus is on Computer Science and Data Science courses (we have indexed over 150k courses so far). I'm adding it under the MOOCs list, as I believe it might be a valuable resource for programmers.
> Add Classpert under the MOOcs list

- README.md
The video doesn't seem to be available anymore, so it's being removed.
This resolves issue #346
> Remove the missing video by Gayle McDowell.

- README.md
The "Breaking the Code: Biography of Alan Turing" is unavailable on youtube. I have updated it to the archive.org link.
> updated broken youtube link

- README.md
The link and intro of "BeehYve : Student crowdsourced resources for any topic" in the "Interview Preparation" section was removed because the link is no longer accessible.
closes #403
> Delete one likely broken link in README.md

- README.md
Added link to https://wandbox.org/ to the Online Compilers section.
Wandbox tends to have bleeding edge C++, .NET, Java and other compilers. It's open source, too.
> Added Wandbox to online compilers

- README.md
Removed double hyphens in #seminar-research-writing-talks-etc link
> fixed seminar link

- README.md
On accessing one reddit link I see below message on post
```
Sorry, this post was deleted by the person who originally posted it.
It doesn't appear in any feeds, and anyone with a direct link to it will see a message like this one.
```
> Removed reddit dead link

- README.md
> It's "Codecademy" not "Codeacademy"

- README.md
I have added programmingbooks.dev to the Computer Books section. programmingbooks.dev aims to help people read more programming books without getting overwhelmed. I hope you like it.
> Add programmingbooks.dev to Computer Books section

- README.md
The CoderPad link is dead so I fixed it, and added another related tool.
> Fixed the CoderPad link, and added Pad.new

- README.md
Added Code Eval link in the README.md
CodeEval is a notepad for notes and code snippets, stored locally in the browser.
[x] My change follows the [Contributing Guidelines](./CONTRIBUTING.md)
[x] I have added only one new link to the list.
[x] I have sorted the link alphabetically under the related section.
> Added Code Eval link

- README.md
Add advent-of-code to competitive-programing section of README.md
According to (a bit of) its about page:
>Advent of Code is an Advent calendar of small programming puzzles for a variety of skill sets and skill levels that can be solved in any programming language you like. People use them as interview prep, company training, university coursework, practice problems, a speed contest, or to challenge each other.
> Add advent-of-code to README.md

- README.md
Add Svix Play to general tools.
Svix Play is a webhook tester & debugger with an API that lets you test webhooks directly from your test suite.
> add Svix Play to General Tools

- README.md
Added a resume template link which help make a ATS friendly resume.
Added this resume template (FAANGPath) in Interview Preparation Section. Resumes are important for appearing in Interviews and I see no such template was provided in this Repo. FAANGPath is built in Openleaf which is known for its good parsing.
Fixes #1761
> FAANGPath Resume template Link in Interview Preparation section

- README.md
Fixes #1886 
- As specified in the issue, the below link in the Interview Section is not reachable:
- [Give your résumé a face lift](http://www.lifeclever.com/give-your-resume-a-face-lift/)
- The link is updated with a new wordpress blog that bears the same name:
- [Give your résumé a face lift](https://motorsh.wordpress.com/2009/01/13/give-your-resume-a-face-lift-from-lifeclever/)
- The link is up and working fine:
> Fix broken link in Interview Section

- README.md
Fixes: #1895 
- As specified in the issue, the link in the "__Learn AI__" section is broken:
- [Unsupervised Sentiment Neuron](https://blog.openai.com/unsupervised-sentiment-neuron/) : Unsupervised Sentiment Neuron
- The link points to a blog on Unsupervised Sentiment Neuron, developed by OpenAI.
- The broken lnk is replaced a working link that points to the correct webpage: 
- [Unsupervised Sentiment Neuron](https://openai.com/research/unsupervised-sentiment-neuron): Unsupervised Sentiment Neuron
> Fix broken link in Learn AI Section

- README.md
#1848 
Issue has been solved.
Changed the Google Code Jam link with an Archive which holds practice questions of Google Code Jam,Kickstart and HashCode.
> Update Google Code Jam link to Google Coding Competitions Archive

- README.md
Improve the description of Ars Technica, fix grammar in some entries.
Some entries were not starting from upper case and some were not ending with period. I have fixed them.
> Improve the description of Ars Technica, fix grammar in some entries

- README.md
Add CORS-Tester to General tools.
Add CORS-Tester to General tools. CORS-Tester is a tool for developers and API testers to check if an API is CORS-enabled for a given domain and identify gaps.
- [ * ] My change follows the [Contributing Guidelines](./CONTRIBUTING.md)
- [ * ] I have added only one new link to the list.
- [ * ] I have checked that the link that I added does NOT exist in the project already.
- [ * ] I have sorted the link alphabetically under the related section.
> Add CORS-Tester to General tools

- README.md
Remove Broken Link  | Missing SSL cert
I removed the https://www.sijinjoseph.com/programmer-competency-matrix/ link 
I was reading through the repo and noticed that the https://www.sijinjoseph.com/programmer-competency-matrix/ link was broken due to a missing SSL certificate. This PR removes the broken link.
> remove https://www.sijinjoseph.com/programmer-competency-matrix/ for
